package com.anakie.restApiBakery.entity;

public enum Status {

    RECEIVED, FUNDED, WITHDRAW,PAID_WITH_ACCOUNT,
    PROCESSING_ORDER ,
    BAKING, OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    ACTIVE,
    NOT_ACTIVE,
    SETTLED,
    REFUNDED,
    NOT_PAID,
    PAID,
    PAID_GOT_CHANGE,
    NEW, SETTLED_WITH_CHANGE

}
